// DEPRECATED !!!!
FROM golang:1.8

MAINTAINER Joan Vega <joan@wetopi.com>

RUN apt-get update \
    && apt-get install -y -q \
       gcc libc-dev \
       librados-dev \
       librbd-dev

COPY . /go/src/github.com/wetopi/docker-volume-rbd
WORKDIR /go/src/github.com/wetopi/docker-volume-rbd

RUN set -ex
RUN go get -u github.com/golang/dep/cmd/dep
RUN dep ensure
RUN go install

CMD ["/go/bin/docker-volume-rbd"]