FROM golang:1.14

MAINTAINER Joan Vega <joan@wetopi.com>

RUN apt-get update \
    && apt-get install -y -q \
       gcc libc-dev \
       librados-dev \
       librbd-dev

RUN go get -u github.com/golang/dep/cmd/dep

VOLUME ["/go/src/github.com/wetopi/docker-volume-rbd"]
WORKDIR /go/src/github.com/wetopi/docker-volume-rbd
